{{- if .Values.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "yardmaster.fullname" . }}-worker
  labels:
    {{- include "yardmaster.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      {{- include "yardmaster.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "yardmaster.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      containers:
        - name: worker
          image: {{ include "yardmaster.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - worker
            - --db
            - {{ .Values.database.dsn | quote }}
            - --name
            - $(POD_NAME)
            {{- range .Values.worker.extraArgs }}
            - {{ . | quote }}
            {{- end }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: YARDMASTER_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "yardmaster.secretName" . }}
                  key: YARDMASTER_ENCRYPTION_KEY
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- end }}
