// The wire protocol between Railwarden and an out-of-process extension. One plugin binary serves
// one Extension service; Describe names what it provides and the remaining calls carry each seam.
// Field numbers are frozen once released, so grow messages by adding fields, never by reusing.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: extension.proto

package extproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DescribeRequest asks the plugin what it provides.
type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_extension_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{0}
}

// DescribeResponse lists the names the plugin registers, per seam. Every name must be unique
// against the host's built-ins and every other loaded plugin.
type DescribeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tools are execution tool names served by RunTool.
	Tools []string `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	// notifiers are notification channel names served by Notify.
	Notifiers []string `protobuf:"bytes,2,rep,name=notifiers,proto3" json:"notifiers,omitempty"`
	// ai_providers are model backend names served by Complete.
	AiProviders []string `protobuf:"bytes,3,rep,name=ai_providers,json=aiProviders,proto3" json:"ai_providers,omitempty"`
	// secret_sources are static secret engine kinds served by ResolveSecret.
	SecretSources []string `protobuf:"bytes,4,rep,name=secret_sources,json=secretSources,proto3" json:"secret_sources,omitempty"`
	// dynamic_secret_sources are dynamic secret engine kinds served by MintSecret.
	DynamicSecretSources []string `protobuf:"bytes,5,rep,name=dynamic_secret_sources,json=dynamicSecretSources,proto3" json:"dynamic_secret_sources,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_extension_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{1}
}

func (x *DescribeResponse) GetTools() []string {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *DescribeResponse) GetNotifiers() []string {
	if x != nil {
		return x.Notifiers
	}
	return nil
}

func (x *DescribeResponse) GetAiProviders() []string {
	if x != nil {
		return x.AiProviders
	}
	return nil
}

func (x *DescribeResponse) GetSecretSources() []string {
	if x != nil {
		return x.SecretSources
	}
	return nil
}

func (x *DescribeResponse) GetDynamicSecretSources() []string {
	if x != nil {
		return x.DynamicSecretSources
	}
	return nil
}

// RunToolRequest carries the run a tool executes.
type RunToolRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tool is the declared tool name the run selected.
	Tool string `protobuf:"bytes,1,opt,name=tool,proto3" json:"tool,omitempty"`
	// command is the tool's primary input, the same field bash and python read their script from.
	Command string `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	// dry_run asks for the tool's no-change mode.
	DryRun bool `protobuf:"varint,3,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	// extra_vars_json is the run's extra vars as one JSON object, empty when the run has none.
	ExtraVarsJson []byte `protobuf:"bytes,4,opt,name=extra_vars_json,json=extraVarsJson,proto3" json:"extra_vars_json,omitempty"`
	// env holds additional KEY=VALUE environment entries for the run.
	Env []string `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty"`
	// dir is the working directory for the run, empty for the host's default.
	Dir           string `protobuf:"bytes,6,opt,name=dir,proto3" json:"dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunToolRequest) Reset() {
	*x = RunToolRequest{}
	mi := &file_extension_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunToolRequest) ProtoMessage() {}

func (x *RunToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunToolRequest.ProtoReflect.Descriptor instead.
func (*RunToolRequest) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{2}
}

func (x *RunToolRequest) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *RunToolRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *RunToolRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

func (x *RunToolRequest) GetExtraVarsJson() []byte {
	if x != nil {
		return x.ExtraVarsJson
	}
	return nil
}

func (x *RunToolRequest) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *RunToolRequest) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

// RunToolReply is one message in the run's reply stream: output while the tool runs, then the
// result as the final message.
type RunToolReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Reply:
	//
	//	*RunToolReply_Output
	//	*RunToolReply_Result
	Reply         isRunToolReply_Reply `protobuf_oneof:"reply"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunToolReply) Reset() {
	*x = RunToolReply{}
	mi := &file_extension_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunToolReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunToolReply) ProtoMessage() {}

func (x *RunToolReply) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunToolReply.ProtoReflect.Descriptor instead.
func (*RunToolReply) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{3}
}

func (x *RunToolReply) GetReply() isRunToolReply_Reply {
	if x != nil {
		return x.Reply
	}
	return nil
}

func (x *RunToolReply) GetOutput() []byte {
	if x != nil {
		if x, ok := x.Reply.(*RunToolReply_Output); ok {
			return x.Output
		}
	}
	return nil
}

func (x *RunToolReply) GetResult() *ToolResult {
	if x != nil {
		if x, ok := x.Reply.(*RunToolReply_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isRunToolReply_Reply interface {
	isRunToolReply_Reply()
}

type RunToolReply_Output struct {
	// output is a chunk of the run's combined output.
	Output []byte `protobuf:"bytes,1,opt,name=output,proto3,oneof"`
}

type RunToolReply_Result struct {
	// result ends the stream with the run's exit code.
	Result *ToolResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

func (*RunToolReply_Output) isRunToolReply_Reply() {}

func (*RunToolReply_Result) isRunToolReply_Reply() {}

// ToolResult is the outcome of a completed tool run.
type ToolResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// exit_code is the run's exit code. Zero means success.
	ExitCode      int32 `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResult) Reset() {
	*x = ToolResult{}
	mi := &file_extension_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResult) ProtoMessage() {}

func (x *ToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResult.ProtoReflect.Descriptor instead.
func (*ToolResult) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{4}
}

func (x *ToolResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

// NotifyRequest carries a terminal run to a notification channel.
type NotifyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// channel is the declared notifier name the delivery targets.
	Channel string `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	// run_json is the terminal run in its v1 API JSON shape, extra vars already redacted.
	RunJson       []byte `protobuf:"bytes,2,opt,name=run_json,json=runJson,proto3" json:"run_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyRequest) Reset() {
	*x = NotifyRequest{}
	mi := &file_extension_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRequest) ProtoMessage() {}

func (x *NotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRequest.ProtoReflect.Descriptor instead.
func (*NotifyRequest) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{5}
}

func (x *NotifyRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *NotifyRequest) GetRunJson() []byte {
	if x != nil {
		return x.RunJson
	}
	return nil
}

// NotifyResponse acknowledges a delivery.
type NotifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyResponse) Reset() {
	*x = NotifyResponse{}
	mi := &file_extension_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyResponse) ProtoMessage() {}

func (x *NotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyResponse.ProtoReflect.Descriptor instead.
func (*NotifyResponse) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{6}
}

// CompleteRequest carries one completion call to an AI provider.
type CompleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// provider is the declared AI provider name.
	Provider string `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	// model is the configured model name.
	Model string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	// url is the configured endpoint URL, empty for the provider's default.
	Url string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	// api_key is the configured API key, empty when the backend needs none.
	ApiKey string `protobuf:"bytes,4,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	// system is the system instruction.
	System string `protobuf:"bytes,5,opt,name=system,proto3" json:"system,omitempty"`
	// user is the user prompt.
	User          string `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteRequest) Reset() {
	*x = CompleteRequest{}
	mi := &file_extension_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRequest) ProtoMessage() {}

func (x *CompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRequest.ProtoReflect.Descriptor instead.
func (*CompleteRequest) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{7}
}

func (x *CompleteRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CompleteRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CompleteRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CompleteRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *CompleteRequest) GetSystem() string {
	if x != nil {
		return x.System
	}
	return ""
}

func (x *CompleteRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

// CompleteResponse carries the provider's reply.
type CompleteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// text is the model's completion.
	Text          string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteResponse) Reset() {
	*x = CompleteResponse{}
	mi := &file_extension_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteResponse) ProtoMessage() {}

func (x *CompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteResponse.ProtoReflect.Descriptor instead.
func (*CompleteResponse) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{8}
}

func (x *CompleteResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// ResolveSecretRequest asks a static secret source for a value.
type ResolveSecretRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kind is the declared secret source kind.
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// config is the source's config string, whose meaning the plugin defines.
	Config        string `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveSecretRequest) Reset() {
	*x = ResolveSecretRequest{}
	mi := &file_extension_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveSecretRequest) ProtoMessage() {}

func (x *ResolveSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveSecretRequest.ProtoReflect.Descriptor instead.
func (*ResolveSecretRequest) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{9}
}

func (x *ResolveSecretRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ResolveSecretRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

// ResolveSecretResponse carries the resolved value.
type ResolveSecretResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// value is the secret value.
	Value         string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveSecretResponse) Reset() {
	*x = ResolveSecretResponse{}
	mi := &file_extension_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveSecretResponse) ProtoMessage() {}

func (x *ResolveSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveSecretResponse.ProtoReflect.Descriptor instead.
func (*ResolveSecretResponse) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{10}
}

func (x *ResolveSecretResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// MintSecretRequest asks a dynamic secret source to mint a short-lived value.
type MintSecretRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kind is the declared dynamic secret source kind.
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// config is the source's config string, whose meaning the plugin defines.
	Config        string `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintSecretRequest) Reset() {
	*x = MintSecretRequest{}
	mi := &file_extension_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintSecretRequest) ProtoMessage() {}

func (x *MintSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintSecretRequest.ProtoReflect.Descriptor instead.
func (*MintSecretRequest) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{11}
}

func (x *MintSecretRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *MintSecretRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

// MintSecretResponse carries the minted value and its lease.
type MintSecretResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// value is the minted secret value.
	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// lease_id names the lease for RevokeLease, empty when the secret only expires on its own TTL.
	LeaseId       string `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintSecretResponse) Reset() {
	*x = MintSecretResponse{}
	mi := &file_extension_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintSecretResponse) ProtoMessage() {}

func (x *MintSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintSecretResponse.ProtoReflect.Descriptor instead.
func (*MintSecretResponse) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{12}
}

func (x *MintSecretResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *MintSecretResponse) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

// RevokeLeaseRequest ends a minted secret early.
type RevokeLeaseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// lease_id is the lease to revoke, as returned by MintSecret.
	LeaseId       string `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeLeaseRequest) Reset() {
	*x = RevokeLeaseRequest{}
	mi := &file_extension_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeLeaseRequest) ProtoMessage() {}

func (x *RevokeLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeLeaseRequest.ProtoReflect.Descriptor instead.
func (*RevokeLeaseRequest) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{13}
}

func (x *RevokeLeaseRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

// RevokeLeaseResponse acknowledges a revocation.
type RevokeLeaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeLeaseResponse) Reset() {
	*x = RevokeLeaseResponse{}
	mi := &file_extension_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeLeaseResponse) ProtoMessage() {}

func (x *RevokeLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeLeaseResponse.ProtoReflect.Descriptor instead.
func (*RevokeLeaseResponse) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{14}
}

var File_extension_proto protoreflect.FileDescriptor

const file_extension_proto_rawDesc = "" +
	"\n" +
	"\x0fextension.proto\x12\x17railwarden.extension.v1\"\x11\n" +
	"\x0fDescribeRequest\"\xc6\x01\n" +
	"\x10DescribeResponse\x12\x14\n" +
	"\x05tools\x18\x01 \x03(\tR\x05tools\x12\x1c\n" +
	"\tnotifiers\x18\x02 \x03(\tR\tnotifiers\x12!\n" +
	"\fai_providers\x18\x03 \x03(\tR\vaiProviders\x12%\n" +
	"\x0esecret_sources\x18\x04 \x03(\tR\rsecretSources\x124\n" +
	"\x16dynamic_secret_sources\x18\x05 \x03(\tR\x14dynamicSecretSources\"\xa3\x01\n" +
	"\x0eRunToolRequest\x12\x12\n" +
	"\x04tool\x18\x01 \x01(\tR\x04tool\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x17\n" +
	"\adry_run\x18\x03 \x01(\bR\x06dryRun\x12&\n" +
	"\x0fextra_vars_json\x18\x04 \x01(\fR\rextraVarsJson\x12\x10\n" +
	"\x03env\x18\x05 \x03(\tR\x03env\x12\x10\n" +
	"\x03dir\x18\x06 \x01(\tR\x03dir\"p\n" +
	"\fRunToolReply\x12\x18\n" +
	"\x06output\x18\x01 \x01(\fH\x00R\x06output\x12=\n" +
	"\x06result\x18\x02 \x01(\v2#.railwarden.extension.v1.ToolResultH\x00R\x06resultB\a\n" +
	"\x05reply\")\n" +
	"\n" +
	"ToolResult\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\"D\n" +
	"\rNotifyRequest\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x19\n" +
	"\brun_json\x18\x02 \x01(\fR\arunJson\"\x10\n" +
	"\x0eNotifyResponse\"\x9a\x01\n" +
	"\x0fCompleteRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x17\n" +
	"\aapi_key\x18\x04 \x01(\tR\x06apiKey\x12\x16\n" +
	"\x06system\x18\x05 \x01(\tR\x06system\x12\x12\n" +
	"\x04user\x18\x06 \x01(\tR\x04user\"&\n" +
	"\x10CompleteResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"B\n" +
	"\x14ResolveSecretRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x16\n" +
	"\x06config\x18\x02 \x01(\tR\x06config\"-\n" +
	"\x15ResolveSecretResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"?\n" +
	"\x11MintSecretRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x16\n" +
	"\x06config\x18\x02 \x01(\tR\x06config\"E\n" +
	"\x12MintSecretResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\tR\aleaseId\"/\n" +
	"\x12RevokeLeaseRequest\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\"\x15\n" +
	"\x13RevokeLeaseResponse2\xc6\x05\n" +
	"\tExtension\x12_\n" +
	"\bDescribe\x12(.railwarden.extension.v1.DescribeRequest\x1a).railwarden.extension.v1.DescribeResponse\x12[\n" +
	"\aRunTool\x12'.railwarden.extension.v1.RunToolRequest\x1a%.railwarden.extension.v1.RunToolReply0\x01\x12Y\n" +
	"\x06Notify\x12&.railwarden.extension.v1.NotifyRequest\x1a'.railwarden.extension.v1.NotifyResponse\x12_\n" +
	"\bComplete\x12(.railwarden.extension.v1.CompleteRequest\x1a).railwarden.extension.v1.CompleteResponse\x12n\n" +
	"\rResolveSecret\x12-.railwarden.extension.v1.ResolveSecretRequest\x1a..railwarden.extension.v1.ResolveSecretResponse\x12e\n" +
	"\n" +
	"MintSecret\x12*.railwarden.extension.v1.MintSecretRequest\x1a+.railwarden.extension.v1.MintSecretResponse\x12h\n" +
	"\vRevokeLease\x12+.railwarden.extension.v1.RevokeLeaseRequest\x1a,.railwarden.extension.v1.RevokeLeaseResponseB2Z0github.com/dcadolph/railwarden/internal/extprotob\x06proto3"

var (
	file_extension_proto_rawDescOnce sync.Once
	file_extension_proto_rawDescData []byte
)

func file_extension_proto_rawDescGZIP() []byte {
	file_extension_proto_rawDescOnce.Do(func() {
		file_extension_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_extension_proto_rawDesc), len(file_extension_proto_rawDesc)))
	})
	return file_extension_proto_rawDescData
}

var file_extension_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_extension_proto_goTypes = []any{
	(*DescribeRequest)(nil),       // 0: railwarden.extension.v1.DescribeRequest
	(*DescribeResponse)(nil),      // 1: railwarden.extension.v1.DescribeResponse
	(*RunToolRequest)(nil),        // 2: railwarden.extension.v1.RunToolRequest
	(*RunToolReply)(nil),          // 3: railwarden.extension.v1.RunToolReply
	(*ToolResult)(nil),            // 4: railwarden.extension.v1.ToolResult
	(*NotifyRequest)(nil),         // 5: railwarden.extension.v1.NotifyRequest
	(*NotifyResponse)(nil),        // 6: railwarden.extension.v1.NotifyResponse
	(*CompleteRequest)(nil),       // 7: railwarden.extension.v1.CompleteRequest
	(*CompleteResponse)(nil),      // 8: railwarden.extension.v1.CompleteResponse
	(*ResolveSecretRequest)(nil),  // 9: railwarden.extension.v1.ResolveSecretRequest
	(*ResolveSecretResponse)(nil), // 10: railwarden.extension.v1.ResolveSecretResponse
	(*MintSecretRequest)(nil),     // 11: railwarden.extension.v1.MintSecretRequest
	(*MintSecretResponse)(nil),    // 12: railwarden.extension.v1.MintSecretResponse
	(*RevokeLeaseRequest)(nil),    // 13: railwarden.extension.v1.RevokeLeaseRequest
	(*RevokeLeaseResponse)(nil),   // 14: railwarden.extension.v1.RevokeLeaseResponse
}
var file_extension_proto_depIdxs = []int32{
	4,  // 0: railwarden.extension.v1.RunToolReply.result:type_name -> railwarden.extension.v1.ToolResult
	0,  // 1: railwarden.extension.v1.Extension.Describe:input_type -> railwarden.extension.v1.DescribeRequest
	2,  // 2: railwarden.extension.v1.Extension.RunTool:input_type -> railwarden.extension.v1.RunToolRequest
	5,  // 3: railwarden.extension.v1.Extension.Notify:input_type -> railwarden.extension.v1.NotifyRequest
	7,  // 4: railwarden.extension.v1.Extension.Complete:input_type -> railwarden.extension.v1.CompleteRequest
	9,  // 5: railwarden.extension.v1.Extension.ResolveSecret:input_type -> railwarden.extension.v1.ResolveSecretRequest
	11, // 6: railwarden.extension.v1.Extension.MintSecret:input_type -> railwarden.extension.v1.MintSecretRequest
	13, // 7: railwarden.extension.v1.Extension.RevokeLease:input_type -> railwarden.extension.v1.RevokeLeaseRequest
	1,  // 8: railwarden.extension.v1.Extension.Describe:output_type -> railwarden.extension.v1.DescribeResponse
	3,  // 9: railwarden.extension.v1.Extension.RunTool:output_type -> railwarden.extension.v1.RunToolReply
	6,  // 10: railwarden.extension.v1.Extension.Notify:output_type -> railwarden.extension.v1.NotifyResponse
	8,  // 11: railwarden.extension.v1.Extension.Complete:output_type -> railwarden.extension.v1.CompleteResponse
	10, // 12: railwarden.extension.v1.Extension.ResolveSecret:output_type -> railwarden.extension.v1.ResolveSecretResponse
	12, // 13: railwarden.extension.v1.Extension.MintSecret:output_type -> railwarden.extension.v1.MintSecretResponse
	14, // 14: railwarden.extension.v1.Extension.RevokeLease:output_type -> railwarden.extension.v1.RevokeLeaseResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_extension_proto_init() }
func file_extension_proto_init() {
	if File_extension_proto != nil {
		return
	}
	file_extension_proto_msgTypes[3].OneofWrappers = []any{
		(*RunToolReply_Output)(nil),
		(*RunToolReply_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_extension_proto_rawDesc), len(file_extension_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_extension_proto_goTypes,
		DependencyIndexes: file_extension_proto_depIdxs,
		MessageInfos:      file_extension_proto_msgTypes,
	}.Build()
	File_extension_proto = out.File
	file_extension_proto_goTypes = nil
	file_extension_proto_depIdxs = nil
}
