// The wire protocol between Yardmaster and an out-of-process extension. One plugin binary serves
// one Extension service; Describe names what it provides and the remaining calls carry each seam.
// Field numbers are frozen once released, so grow messages by adding fields, never by reusing.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: extension.proto

package extproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Extension_Describe_FullMethodName      = "/yardmaster.extension.v1.Extension/Describe"
	Extension_RunTool_FullMethodName       = "/yardmaster.extension.v1.Extension/RunTool"
	Extension_Notify_FullMethodName        = "/yardmaster.extension.v1.Extension/Notify"
	Extension_Complete_FullMethodName      = "/yardmaster.extension.v1.Extension/Complete"
	Extension_ResolveSecret_FullMethodName = "/yardmaster.extension.v1.Extension/ResolveSecret"
	Extension_MintSecret_FullMethodName    = "/yardmaster.extension.v1.Extension/MintSecret"
	Extension_RevokeLease_FullMethodName   = "/yardmaster.extension.v1.Extension/RevokeLease"
)

// ExtensionClient is the client API for Extension service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Extension is the single service a plugin binary serves. A plugin implements only the calls for
// the seams it declares in Describe; the rest return an unimplemented error.
type ExtensionClient interface {
	// Describe names everything the plugin provides, so the host can register each seam.
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error)
	// RunTool executes one run of a declared tool, streaming output and ending with the result.
	RunTool(ctx context.Context, in *RunToolRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunToolReply], error)
	// Notify delivers a terminal run to a declared notification channel.
	Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error)
	// Complete returns a declared AI provider's reply to a system instruction and a user prompt.
	Complete(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*CompleteResponse, error)
	// ResolveSecret fetches a value from a declared static secret source.
	ResolveSecret(ctx context.Context, in *ResolveSecretRequest, opts ...grpc.CallOption) (*ResolveSecretResponse, error)
	// MintSecret mints a short-lived value from a declared dynamic secret source.
	MintSecret(ctx context.Context, in *MintSecretRequest, opts ...grpc.CallOption) (*MintSecretResponse, error)
	// RevokeLease ends a minted secret early by the lease id MintSecret returned.
	RevokeLease(ctx context.Context, in *RevokeLeaseRequest, opts ...grpc.CallOption) (*RevokeLeaseResponse, error)
}

type extensionClient struct {
	cc grpc.ClientConnInterface
}

func NewExtensionClient(cc grpc.ClientConnInterface) ExtensionClient {
	return &extensionClient{cc}
}

func (c *extensionClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeResponse)
	err := c.cc.Invoke(ctx, Extension_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionClient) RunTool(ctx context.Context, in *RunToolRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunToolReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Extension_ServiceDesc.Streams[0], Extension_RunTool_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunToolRequest, RunToolReply]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Extension_RunToolClient = grpc.ServerStreamingClient[RunToolReply]

func (c *extensionClient) Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyResponse)
	err := c.cc.Invoke(ctx, Extension_Notify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionClient) Complete(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*CompleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteResponse)
	err := c.cc.Invoke(ctx, Extension_Complete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionClient) ResolveSecret(ctx context.Context, in *ResolveSecretRequest, opts ...grpc.CallOption) (*ResolveSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveSecretResponse)
	err := c.cc.Invoke(ctx, Extension_ResolveSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionClient) MintSecret(ctx context.Context, in *MintSecretRequest, opts ...grpc.CallOption) (*MintSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MintSecretResponse)
	err := c.cc.Invoke(ctx, Extension_MintSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionClient) RevokeLease(ctx context.Context, in *RevokeLeaseRequest, opts ...grpc.CallOption) (*RevokeLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeLeaseResponse)
	err := c.cc.Invoke(ctx, Extension_RevokeLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExtensionServer is the server API for Extension service.
// All implementations must embed UnimplementedExtensionServer
// for forward compatibility.
//
// Extension is the single service a plugin binary serves. A plugin implements only the calls for
// the seams it declares in Describe; the rest return an unimplemented error.
type ExtensionServer interface {
	// Describe names everything the plugin provides, so the host can register each seam.
	Describe(context.Context, *DescribeRequest) (*DescribeResponse, error)
	// RunTool executes one run of a declared tool, streaming output and ending with the result.
	RunTool(*RunToolRequest, grpc.ServerStreamingServer[RunToolReply]) error
	// Notify delivers a terminal run to a declared notification channel.
	Notify(context.Context, *NotifyRequest) (*NotifyResponse, error)
	// Complete returns a declared AI provider's reply to a system instruction and a user prompt.
	Complete(context.Context, *CompleteRequest) (*CompleteResponse, error)
	// ResolveSecret fetches a value from a declared static secret source.
	ResolveSecret(context.Context, *ResolveSecretRequest) (*ResolveSecretResponse, error)
	// MintSecret mints a short-lived value from a declared dynamic secret source.
	MintSecret(context.Context, *MintSecretRequest) (*MintSecretResponse, error)
	// RevokeLease ends a minted secret early by the lease id MintSecret returned.
	RevokeLease(context.Context, *RevokeLeaseRequest) (*RevokeLeaseResponse, error)
	mustEmbedUnimplementedExtensionServer()
}

// UnimplementedExtensionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExtensionServer struct{}

func (UnimplementedExtensionServer) Describe(context.Context, *DescribeRequest) (*DescribeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedExtensionServer) RunTool(*RunToolRequest, grpc.ServerStreamingServer[RunToolReply]) error {
	return status.Errorf(codes.Unimplemented, "method RunTool not implemented")
}
func (UnimplementedExtensionServer) Notify(context.Context, *NotifyRequest) (*NotifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Notify not implemented")
}
func (UnimplementedExtensionServer) Complete(context.Context, *CompleteRequest) (*CompleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Complete not implemented")
}
func (UnimplementedExtensionServer) ResolveSecret(context.Context, *ResolveSecretRequest) (*ResolveSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveSecret not implemented")
}
func (UnimplementedExtensionServer) MintSecret(context.Context, *MintSecretRequest) (*MintSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MintSecret not implemented")
}
func (UnimplementedExtensionServer) RevokeLease(context.Context, *RevokeLeaseRequest) (*RevokeLeaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeLease not implemented")
}
func (UnimplementedExtensionServer) mustEmbedUnimplementedExtensionServer() {}
func (UnimplementedExtensionServer) testEmbeddedByValue()                   {}

// UnsafeExtensionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExtensionServer will
// result in compilation errors.
type UnsafeExtensionServer interface {
	mustEmbedUnimplementedExtensionServer()
}

func RegisterExtensionServer(s grpc.ServiceRegistrar, srv ExtensionServer) {
	// If the following call pancis, it indicates UnimplementedExtensionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Extension_ServiceDesc, srv)
}

func _Extension_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Extension_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServer).Describe(ctx, req.(*DescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Extension_RunTool_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunToolRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ExtensionServer).RunTool(m, &grpc.GenericServerStream[RunToolRequest, RunToolReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Extension_RunToolServer = grpc.ServerStreamingServer[RunToolReply]

func _Extension_Notify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServer).Notify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Extension_Notify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServer).Notify(ctx, req.(*NotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Extension_Complete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServer).Complete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Extension_Complete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServer).Complete(ctx, req.(*CompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Extension_ResolveSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServer).ResolveSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Extension_ResolveSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServer).ResolveSecret(ctx, req.(*ResolveSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Extension_MintSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MintSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServer).MintSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Extension_MintSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServer).MintSecret(ctx, req.(*MintSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Extension_RevokeLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServer).RevokeLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Extension_RevokeLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServer).RevokeLease(ctx, req.(*RevokeLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Extension_ServiceDesc is the grpc.ServiceDesc for Extension service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Extension_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "yardmaster.extension.v1.Extension",
	HandlerType: (*ExtensionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _Extension_Describe_Handler,
		},
		{
			MethodName: "Notify",
			Handler:    _Extension_Notify_Handler,
		},
		{
			MethodName: "Complete",
			Handler:    _Extension_Complete_Handler,
		},
		{
			MethodName: "ResolveSecret",
			Handler:    _Extension_ResolveSecret_Handler,
		},
		{
			MethodName: "MintSecret",
			Handler:    _Extension_MintSecret_Handler,
		},
		{
			MethodName: "RevokeLease",
			Handler:    _Extension_RevokeLease_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunTool",
			Handler:       _Extension_RunTool_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "extension.proto",
}
