package ansibleruntime

import (
	"errors"
	"fmt"
	"strings"
	"testing"
)

// TestParseLockRefusesLinesOnlyPipSees pins that the lock check reads lines the way pip does.
// pip splits a requirements file with Python's str.splitlines, which also breaks lines at a
// carriage return, a vertical tab, a form feed, the separators 0x1c to 0x1e, NEL, and the Unicode
// line and paragraph separators. ParseLock splits at newlines only, so any of those inside a
// comment hides an option line from the check that pip then obeys: -r adds packages of the
// author's choosing with their own hashes, and --index-url or --find-links moves where files come
// from. pip 26.2.1's own preprocess was shown to return the hidden -r and --index-url lines.
func TestParseLockRefusesLinesOnlyPipSees(t *testing.T) {
	t.Parallel()
	base, err := LockFor("2.21")
	if err != nil {
		t.Fatalf("LockFor() error = %v", err)
	}
	hash := strings.Repeat("a", 64)
	tests := []struct {
		Want  error
		Added string
	}{{ // Test 0: A carriage return in a comment line hides -r.
		Added: "# regenerated\r-r extra.txt\n", Want: ErrLock,
	}, { // Test 1: A form feed in a comment line hides --index-url.
		Added: "# regenerated\f--index-url https://mirror.invalid/simple\n", Want: ErrLock,
	}, { // Test 2: A line separator in a comment line hides an editable requirement.
		Added: "# regenerated -e git+https://example.invalid/pkg.git#egg=pkg\n", Want: ErrLock,
	}, { // Test 3: A file separator after a requirement's comment hides --find-links.
		Added: "six==1.17.0 --hash=sha256:" + hash + " # pinned\x1c--find-links /srv/planted\n",
		Want:  ErrLock,
	}, { // Test 4: An ordinary comment is still accepted.
		Added: "# regenerated by hand\n",
	}}
	for testNum, test := range tests {
		t.Run(fmt.Sprintf("test %d", testNum), func(t *testing.T) {
			t.Parallel()
			content := append([]byte(test.Added), base.Content...)
			_, err := ParseLock(content)
			if !errors.Is(err, test.Want) {
				t.Errorf("ParseLock() error = %v, want %v", err, test.Want)
			}
		})
	}
}
