package sqlitestore_test

import (
	"context"
	"database/sql"
	"path/filepath"
	"testing"
	"time"

	"github.com/go-jose/go-jose/v4"
	"github.com/google/go-cmp/cmp"

	"github.com/kordloom/switchtender/internal/credential"
	"github.com/kordloom/switchtender/internal/federation"
	"github.com/kordloom/switchtender/internal/federationtest"
	"github.com/kordloom/switchtender/internal/sqlitestore"
	"github.com/kordloom/switchtender/internal/sqlutil"
)

// fedChangeSealer seals the keys of the upgraded install's issuer.
var fedChangeSealer = credential.NewSealer("fed-change-passphrase", "fed-change-salt")

// fedChangeReplicas opens two handles on one database file, each with its own write connection, as
// a server and a command run against the database it serves do.
func fedChangeReplicas(t *testing.T) (federation.KeyStore, federation.KeyStore) {
	t.Helper()
	path := filepath.Join(t.TempDir(), "switchtender.db")
	var out []federation.KeyStore
	for range 2 {
		db, err := sqlitestore.Open(path)
		if err != nil {
			t.Fatalf("Open() error = %v", err)
		}
		t.Cleanup(func() { _ = db.Close() })
		out = append(out, db.FederationKeys())
	}
	return out[0], out[1]
}

// TestFederationIssuerContractOnSQLite runs the issuer's cross-process promises on two handles
// sharing one SQLite database file.
func TestFederationIssuerContractOnSQLite(t *testing.T) {
	t.Parallel()
	federationtest.IssuerContract(t, fedChangeReplicas)
}

// fedChangeEarlierKey returns a key generated by an issuer of its own, with its sealed private
// half, standing for a key an earlier build stored.
func fedChangeEarlierKey(t *testing.T) *federation.Key {
	t.Helper()
	store := federation.NewMemKeyStore()
	iss, err := federation.NewIssuer(fedUpgradeIssuerURL, store, fedChangeSealer)
	if err != nil {
		t.Fatalf("NewIssuer() error = %v", err)
	}
	if err := iss.Ensure(context.Background()); err != nil {
		t.Fatalf("Ensure() error = %v", err)
	}
	keys, err := store.List(context.Background())
	if err != nil || len(keys) != 1 {
		t.Fatalf("List() = %d keys, %v, want one", len(keys), err)
	}
	return keys[0]
}

// TestFederationKeysKeepTheirMeaningAcrossTheLifecycleColumnHeal is an install upgraded from a
// build whose federation_keys table had no activation or removal time, holding the key it signs
// with and a key it retired. The heal gives both the times that build meant: each key activated at
// its creation, and the retired key removed a grace period after it retired. The upgraded install
// keeps signing with the key every cloud already fetched, generates no key of its own, and erases
// the private half of the retired key, whose removal has long come.
func TestFederationKeysKeepTheirMeaningAcrossTheLifecycleColumnHeal(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	retiredKey, signingKey := fedChangeEarlierKey(t), fedChangeEarlierKey(t)
	retiredCreated := time.Date(2026, 8, 1, 9, 0, 0, 0, time.UTC)
	retiredAt := time.Date(2026, 9, 1, 9, 0, 0, 0, time.UTC)
	signingCreated := retiredAt

	path := filepath.Join(t.TempDir(), "switchtender.db")
	db, err := sqlitestore.Open(path)
	if err != nil {
		t.Fatalf("Open() error = %v", err)
	}
	if err := db.Close(); err != nil {
		t.Fatalf("Close() error = %v", err)
	}
	raw, err := sql.Open("sqlite", path)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	for _, stmt := range []string{
		"ALTER TABLE federation_keys DROP COLUMN activated_at",
		"ALTER TABLE federation_keys DROP COLUMN removed_at",
	} {
		if _, err := raw.Exec(stmt); err != nil {
			t.Fatalf("simulate the earlier table, %s: %v", stmt, err)
		}
	}
	for _, row := range []struct {
		// Key is the key the earlier build stored.
		Key *federation.Key
		// Created and Retired are its times, Retired empty for the key that signs.
		Created, Retired string
	}{
		{retiredKey, sqlutil.FormatTime(retiredCreated), sqlutil.FormatTime(retiredAt)},
		{signingKey, sqlutil.FormatTime(signingCreated), ""},
	} {
		if _, err := raw.Exec("INSERT INTO federation_keys (id, algorithm, public_key, sealed, "+
			"created_at, retired_at) VALUES (?, ?, ?, ?, ?, ?)", row.Key.ID, row.Key.Algorithm,
			row.Key.PublicKey, row.Key.Sealed, row.Created, row.Retired); err != nil {
			t.Fatalf("store a key the earlier build wrote: %v", err)
		}
	}
	if err := raw.Close(); err != nil {
		t.Fatalf("close raw: %v", err)
	}

	healed, err := sqlitestore.Open(path)
	if err != nil {
		t.Fatalf("reopen: %v", err)
	}
	t.Cleanup(func() { _ = healed.Close() })
	keys, err := healed.FederationKeys().List(ctx)
	if err != nil {
		t.Fatalf("List() after the heal error = %v", err)
	}
	removal := retiredAt.Add(federation.RetiredKeyGrace)
	want := []*federation.Key{{
		ID: retiredKey.ID, Algorithm: "RS256", PublicKey: retiredKey.PublicKey,
		Sealed: retiredKey.Sealed, CreatedAt: retiredCreated, ActivatedAt: &retiredCreated,
		RetiredAt: &retiredAt, RemovedAt: &removal,
	}, {
		ID: signingKey.ID, Algorithm: "RS256", PublicKey: signingKey.PublicKey,
		Sealed: signingKey.Sealed, CreatedAt: signingCreated, ActivatedAt: &signingCreated,
	}}
	if diff := cmp.Diff(want, keys); diff != "" {
		t.Fatalf("the earlier keys after the heal (-want +got):\n%s", diff)
	}

	iss, err := federation.NewIssuer(fedUpgradeIssuerURL, healed.FederationKeys(), fedChangeSealer)
	if err != nil {
		t.Fatalf("NewIssuer() error = %v", err)
	}
	if err := iss.Ensure(ctx); err != nil {
		t.Fatalf("Ensure() after the upgrade error = %v", err)
	}
	token, _, err := iss.Mint(ctx, fedUpgradeClaims(), federation.DefaultTokenTTL)
	if err != nil {
		t.Fatalf("Mint() after the upgrade error = %v", err)
	}
	jws, err := jose.ParseSigned(token, []jose.SignatureAlgorithm{jose.RS256})
	if err != nil {
		t.Fatalf("ParseSigned() error = %v", err)
	}
	if kid := jws.Signatures[0].Header.KeyID; kid != signingKey.ID {
		t.Errorf("after the upgrade the install signs with %s, want %s, the key it signed with "+
			"before", kid, signingKey.ID)
	}
	infos, err := iss.Keys(ctx)
	if err != nil {
		t.Fatalf("Keys() error = %v", err)
	}
	states := map[string]string{}
	for _, k := range infos {
		states[k.ID] = k.State
	}
	wantStates := map[string]string{retiredKey.ID: federation.StateRemoved,
		signingKey.ID: federation.StateSigning}
	if diff := cmp.Diff(wantStates, states); diff != "" {
		t.Errorf("key states after the upgrade (-want +got):\n%s", diff)
	}
	after, err := healed.FederationKeys().List(ctx)
	if err != nil {
		t.Fatalf("List() error = %v", err)
	}
	for _, k := range after {
		if k.ID == retiredKey.ID && k.Sealed != "" {
			t.Error("the retired key's private half outlived its removal after the upgrade")
		}
	}
}
